name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: [self-hosted, Windows]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check workspace
        shell: powershell
        run: |
          Write-Host "Workspace:"
          Write-Host $env:GITHUB_WORKSPACE

          Write-Host "`nCurrent directory:"
          Get-Location

          Write-Host "`nFiles:"
          Get-ChildItem -Force

          Write-Host "`nAll TF files:"
          Get-ChildItem -Path $env:GITHUB_WORKSPACE -Filter *.tf -Recurse

      - name: Terraform Version
        run: terraform version

      - name: Terraform Init
        shell: powershell
        run: terraform init

      - name: Terraform Plan
        shell: powershell
        run: terraform plan
